### PR TITLE
Update deprecated functions

### PR DESCRIPTION
**Pull request by ado21**
This if fixing most of the deprecated functions. 
Found one bug so far which causes that icons for DRs are not showing up. If I ll figure it out faster than you I ll update PR.

My hint is ACE3.0 libs requires to be updated because atm they still use deprecated functions. 
self.db seems to be empty

### CODE REVIEW

**Comment by vendethiel** [comment]
Thanks for the patch. However, to support both classic and retail, I’d prefer toplevel local aliases in the form of `local GetSpellInfo = C_Spell and C_Spell.GetSpellInfo or GetSpellInfo`. This would also reduce the diff. Thanks!

**Comment by vendethiel** [comment]
Actually, this needs a wrapper either way to change how the data is returned

**Comment by ado21** [comment]
I think all of the files changed are used by all wow versions, I have not touched any of the files referring to specific expansion so that should work, shouldnt it ?

**Comment by vendethiel** [comment]
Heads up, #104 looks to be a further along than this PR. I think I'd recommend holding off on extra work for now. Thanks for the help nevertheless!

**Comment by ado21** [comment]
I have finished it right now with wrappers, if you are interested I can post here and simply pick better idea

**Comment by vendethiel** [comment]
If it's no extra work for you, please do! Otherwise it's fine. Thanks!

**Pull request closed without merging**
